# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: happyco/inspect/template/v1/template.proto

require 'google/protobuf'

require 'happyco/type/v1/integration_id_pb'
require 'happyco/type/v1/paging_pb'
require 'happyco/type/v1/varia_pb'
require 'happyco/inspect/type/v1/inspect_type_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "happyco.inspect.template.v1.Template" do
    optional :id, :message, 1, "happyco.type.v1.IntegrationID"
    optional :account_id, :message, 2, "happyco.type.v1.IntegrationID"
    optional :folder_id, :message, 3, "happyco.type.v1.IntegrationID"
    optional :name, :string, 4
    optional :edition, :int32, 5
    optional :description, :string, 6
    map :sections, :string, :message, 7, "happyco.inspect.type.v1.Section"
    map :outlines, :string, :message, 8, "happyco.type.v1.StringArray"
    map :rating_groups, :string, :message, 9, "happyco.inspect.type.v1.RatingGroups"
    repeated :header_fields, :message, 10, "happyco.inspect.type.v1.HeaderField"
    repeated :footer_fields, :message, 11, "happyco.inspect.type.v1.FooterField"
  end
  add_message "happyco.inspect.template.v1.ListTemplatesRequest" do
    optional :account_id, :message, 1, "happyco.type.v1.IntegrationID"
    repeated :folder_ids, :message, 2, "happyco.type.v1.IntegrationID"
    repeated :template_ids, :message, 3, "happyco.type.v1.IntegrationID"
    optional :archived, :bool, 4
    optional :paging, :message, 5, "happyco.type.v1.Paging"
  end
  add_message "happyco.inspect.template.v1.ListTemplatesResponse" do
    repeated :templates, :message, 1, "happyco.inspect.template.v1.Template"
    optional :previous_page, :message, 2, "happyco.type.v1.Paging"
    optional :next_page, :message, 3, "happyco.type.v1.Paging"
  end
  add_message "happyco.inspect.template.v1.CreateTemplatesRequest" do
    optional :account_id, :message, 1, "happyco.type.v1.IntegrationID"
    optional :folder_id, :message, 2, "happyco.type.v1.IntegrationID"
    repeated :templates, :message, 3, "happyco.inspect.template.v1.Template"
  end
  add_message "happyco.inspect.template.v1.CreateTemplatesResponse" do
    repeated :template_ids, :message, 1, "happyco.type.v1.IntegrationID"
  end
  add_message "happyco.inspect.template.v1.UpdateTemplatesRequest" do
    optional :account_id, :message, 1, "happyco.type.v1.IntegrationID"
    optional :folder_id, :message, 2, "happyco.type.v1.IntegrationID"
    repeated :templates, :message, 3, "happyco.inspect.template.v1.Template"
  end
  add_message "happyco.inspect.template.v1.UpdateTemplatesResponse" do
  end
  add_message "happyco.inspect.template.v1.SetTemplatesArchivedRequest" do
    optional :account_id, :message, 1, "happyco.type.v1.IntegrationID"
    optional :folder_id, :message, 2, "happyco.type.v1.IntegrationID"
    repeated :template_ids, :message, 3, "happyco.type.v1.IntegrationID"
  end
  add_message "happyco.inspect.template.v1.SetTemplatesArchivedResponse" do
  end
end

module Happyco
  module Inspect
    module Template
      module V1
        Template = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.inspect.template.v1.Template").msgclass
        ListTemplatesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.inspect.template.v1.ListTemplatesRequest").msgclass
        ListTemplatesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.inspect.template.v1.ListTemplatesResponse").msgclass
        CreateTemplatesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.inspect.template.v1.CreateTemplatesRequest").msgclass
        CreateTemplatesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.inspect.template.v1.CreateTemplatesResponse").msgclass
        UpdateTemplatesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.inspect.template.v1.UpdateTemplatesRequest").msgclass
        UpdateTemplatesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.inspect.template.v1.UpdateTemplatesResponse").msgclass
        SetTemplatesArchivedRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.inspect.template.v1.SetTemplatesArchivedRequest").msgclass
        SetTemplatesArchivedResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.inspect.template.v1.SetTemplatesArchivedResponse").msgclass
      end
    end
  end
end
