# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: happyco/manage/folder/v1/folder.proto for package 'happyco.manage.folder.v1'

require 'grpc'
require 'happyco/manage/folder/v1/folder_pb'

module Happyco
  module Manage
    module Folder
      module V1
        module FolderService
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'happyco.manage.folder.v1.FolderService'

            rpc :ListFolders, ListFoldersRequest, ListFoldersResponse
            rpc :CreateFolders, CreateFoldersRequest, CreateFoldersResponse
            rpc :UpdateFolders, UpdateFoldersRequest, UpdateFoldersResponse
            rpc :UpdateFolderStatuses, UpdateFolderStatusesRequest, UpdateFolderStatusesResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
