# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: happyco/manage/account_provisioning/v1/account_provisioning.proto

require 'google/protobuf'

require 'happyco/manage/account/v1/account_pb'
require 'happyco/type/v1/integration_id_pb'
require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "happyco.manage.account_provisioning.v1.CreateAccountsRequest" do
    repeated :account_with_admins, :message, 1, "happyco.manage.account_provisioning.v1.CreateAccountsRequest.AccountWithAdmin"
  end
  add_message "happyco.manage.account_provisioning.v1.CreateAccountsRequest.AccountWithAdmin" do
    optional :account, :message, 2, "happyco.manage.account.v1.Account"
    optional :admin, :message, 3, "happyco.manage.account.v1.User"
  end
  add_message "happyco.manage.account_provisioning.v1.CreateAccountsResponse" do
    repeated :account_id_with_admin_ids, :message, 1, "happyco.manage.account_provisioning.v1.CreateAccountsResponse.AccountIDWithAdminID"
  end
  add_message "happyco.manage.account_provisioning.v1.CreateAccountsResponse.AccountIDWithAdminID" do
    optional :account_id, :message, 1, "happyco.type.v1.IntegrationID"
    optional :admin_id, :message, 2, "happyco.type.v1.IntegrationID"
  end
  add_message "happyco.manage.account_provisioning.v1.UpdateAccountStatusesRequest" do
    repeated :account_ids, :message, 1, "happyco.type.v1.IntegrationID"
    optional :active, :bool, 2
  end
  add_message "happyco.manage.account_provisioning.v1.UpdateAccountStatusesResponse" do
  end
end

module Happyco
  module Manage
    module AccountProvisioning
      module V1
        CreateAccountsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.account_provisioning.v1.CreateAccountsRequest").msgclass
        CreateAccountsRequest::AccountWithAdmin = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.account_provisioning.v1.CreateAccountsRequest.AccountWithAdmin").msgclass
        CreateAccountsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.account_provisioning.v1.CreateAccountsResponse").msgclass
        CreateAccountsResponse::AccountIDWithAdminID = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.account_provisioning.v1.CreateAccountsResponse.AccountIDWithAdminID").msgclass
        UpdateAccountStatusesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.account_provisioning.v1.UpdateAccountStatusesRequest").msgclass
        UpdateAccountStatusesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.account_provisioning.v1.UpdateAccountStatusesResponse").msgclass
      end
    end
  end
end
