# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: happyco/manage/account_provisioning/v1/account_provisioning.proto for package 'happyco.manage.account_provisioning.v1'

require 'grpc'
require 'happyco/manage/account_provisioning/v1/account_provisioning_pb'

module Happyco
  module Manage
    module AccountProvisioning
      module V1
        module AccountProvisioningService
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'happyco.manage.account_provisioning.v1.AccountProvisioningService'

            rpc :CreateAccounts, CreateAccountsRequest, CreateAccountsResponse
            rpc :UpdateAccountStatuses, UpdateAccountStatusesRequest, UpdateAccountStatusesResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
