# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: happyco/manage/asset/v1/asset.proto

require 'google/protobuf'

require 'happyco/type/v1/integration_id_pb'
require 'happyco/type/v1/paging_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "happyco.manage.asset.v1.Asset" do
    optional :id, :message, 1, "happyco.type.v1.IntegrationID"
    optional :archived, :bool, 2
    optional :address_line_1, :string, 3
    optional :address_line_2, :string, 4
    optional :city, :string, 5
    optional :state, :string, 6
    optional :postal_code, :string, 7
    optional :country, :string, 8
    oneof :type do
      optional :unit, :message, 9, "happyco.manage.asset.v1.Unit"
      optional :property, :message, 10, "happyco.manage.asset.v1.Property"
    end
  end
  add_message "happyco.manage.asset.v1.Unit" do
    optional :building, :string, 1
    optional :floor_plan, :string, 2
  end
  add_message "happyco.manage.asset.v1.Property" do
    optional :key_number, :string, 1
  end
  add_message "happyco.manage.asset.v1.ListAssetsRequest" do
    optional :account_id, :message, 1, "happyco.type.v1.IntegrationID"
    optional :folder_id, :message, 2, "happyco.type.v1.IntegrationID"
    repeated :asset_ids, :message, 3, "happyco.type.v1.IntegrationID"
    optional :include_archived, :bool, 4
    optional :paging, :message, 5, "happyco.type.v1.Paging"
  end
  add_message "happyco.manage.asset.v1.ListAssetsResponse" do
    repeated :assets, :message, 1, "happyco.manage.asset.v1.Asset"
    optional :paging, :message, 2, "happyco.type.v1.PagingResponse"
  end
  add_message "happyco.manage.asset.v1.CreateAssetsRequest" do
    optional :account_id, :message, 1, "happyco.type.v1.IntegrationID"
    optional :folder_id, :message, 2, "happyco.type.v1.IntegrationID"
    repeated :assets, :message, 3, "happyco.manage.asset.v1.Asset"
  end
  add_message "happyco.manage.asset.v1.CreateAssetsResponse" do
    repeated :asset_ids, :message, 1, "happyco.type.v1.IntegrationID"
  end
  add_message "happyco.manage.asset.v1.UpdateAssetsRequest" do
    optional :account_id, :message, 1, "happyco.type.v1.IntegrationID"
    optional :folder_id, :message, 2, "happyco.type.v1.IntegrationID"
    repeated :assets, :message, 3, "happyco.manage.asset.v1.Asset"
  end
  add_message "happyco.manage.asset.v1.UpdateAssetsResponse" do
  end
  add_message "happyco.manage.asset.v1.SetAssetsArchivedRequest" do
    optional :account_id, :message, 1, "happyco.type.v1.IntegrationID"
    optional :folder_id, :message, 2, "happyco.type.v1.IntegrationID"
    repeated :asset_ids, :message, 3, "happyco.type.v1.IntegrationID"
  end
  add_message "happyco.manage.asset.v1.SetAssetsArchivedResponse" do
  end
end

module Happyco
  module Manage
    module Asset
      module V1
        Asset = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.asset.v1.Asset").msgclass
        Unit = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.asset.v1.Unit").msgclass
        Property = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.asset.v1.Property").msgclass
        ListAssetsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.asset.v1.ListAssetsRequest").msgclass
        ListAssetsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.asset.v1.ListAssetsResponse").msgclass
        CreateAssetsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.asset.v1.CreateAssetsRequest").msgclass
        CreateAssetsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.asset.v1.CreateAssetsResponse").msgclass
        UpdateAssetsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.asset.v1.UpdateAssetsRequest").msgclass
        UpdateAssetsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.asset.v1.UpdateAssetsResponse").msgclass
        SetAssetsArchivedRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.asset.v1.SetAssetsArchivedRequest").msgclass
        SetAssetsArchivedResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.manage.asset.v1.SetAssetsArchivedResponse").msgclass
      end
    end
  end
end
