# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: happyco/manage/asset/v1/asset.proto for package 'happyco.manage.asset.v1'

require 'grpc'
require 'happyco/manage/asset/v1/asset_pb'

module Happyco
  module Manage
    module Asset
      module V1
        module AssetService
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'happyco.manage.asset.v1.AssetService'

            rpc :ListAssets, ListAssetsRequest, ListAssetsResponse
            rpc :CreateAssets, CreateAssetsRequest, CreateAssetsResponse
            rpc :UpdateAssets, UpdateAssetsRequest, UpdateAssetsResponse
            rpc :ArchiveAssets, SetAssetsArchivedRequest, SetAssetsArchivedResponse
            rpc :UnarchiveAssets, SetAssetsArchivedRequest, SetAssetsArchivedResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
