# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: happyco/type/v1/date.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "happyco.type.v1.Date" do
    optional :year, :int32, 1
    optional :month, :int32, 2
    optional :day, :int32, 3
  end
end

module Happyco
  module Type
    module V1
      Date = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.type.v1.Date").msgclass
    end
  end
end
