# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: happyco/type/v1/event.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "happyco.type.v1.EventHandlerOptions" do
    optional :ack_timeout_seconds, :int32, 1
  end
  add_message "happyco.type.v1.Event" do
    optional :id, :int32, 1
  end
  add_message "happyco.type.v1.EventAck" do
    repeated :event_ids, :int32, 1
    oneof :ack_message do
      optional :ack, :bool, 2
      optional :extend_timeout_seconds, :int32, 3
    end
  end
end

module Happyco
  module Type
    module V1
      EventHandlerOptions = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.type.v1.EventHandlerOptions").msgclass
      Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.type.v1.Event").msgclass
      EventAck = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.type.v1.EventAck").msgclass
    end
  end
end
