# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: happyco/type/v1/integration_id.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "happyco.type.v1.IntegrationID" do
    optional :id, :string, 1
    optional :external_id, :string, 2
    optional :sync_token, :int32, 3
  end
end

module Happyco
  module Type
    module V1
      IntegrationID = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.type.v1.IntegrationID").msgclass
    end
  end
end
