# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: happyco/type/v1/paging.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "happyco.type.v1.Paging" do
  end
  add_message "happyco.type.v1.PagingResponse" do
  end
end

module Happyco
  module Type
    module V1
      Paging = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.type.v1.Paging").msgclass
      PagingResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.type.v1.PagingResponse").msgclass
    end
  end
end
