# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: happyco/type/v1/varia.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "happyco.type.v1.StringArray" do
    repeated :values, :string, 1
  end
  add_message "happyco.type.v1.FloatArray" do
    repeated :values, :float, 1
  end
end

module Happyco
  module Type
    module V1
      StringArray = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.type.v1.StringArray").msgclass
      FloatArray = Google::Protobuf::DescriptorPool.generated_pool.lookup("happyco.type.v1.FloatArray").msgclass
    end
  end
end
