# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: happyco/manage/account/v1/account.proto for package 'happyco.manage.account.v1'

require 'grpc'
require 'happyco/manage/account/v1/account_pb'

module Happyco
  module Manage
    module Account
      module V1
        module AccountService
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'happyco.manage.account.v1.AccountService'

            rpc :ListAccounts, ListAccountsRequest, ListAccountsResponse
            rpc :UpdateAccounts, UpdateAccountsRequest, UpdateAccountsResponse
          end

          Stub = Service.rpc_stub_class
        end
        module AccountUsersService
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'happyco.manage.account.v1.AccountUsersService'

            rpc :ListUsers, ListUsersRequest, ListUsersResponse
            rpc :AddUsers, AddUsersRequest, AddUsersResponse
            rpc :UpdateUsers, UpdateUsersRequest, UpdateUsersResponse
            rpc :UpdateUserStatuses, UpdateUserStatusesRequest, UpdateUserStatusesResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
